smol = true
logLevel = "error"

[install]
optional = true
dev = true
peer = true
production = false
auto = "auto"
frozenLockfile = false
dryRun = false

[install.lockfile]
save = true

[test]
root = "./src"
preload = ["./setup.ts"]
coverage = true
# to require 90% line-level and function-level coverage
# coverageThreshold = 0.9

